TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REG u8 REG_RDI
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REG i4 REG_RSI
TACO_ADD
  TACA_FRAME u8 0
  TACA_IMM i4 4
TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REF u8 2
TACO_SUB
  TACA_FRAME u8 0
  TACA_IMM i4 4
TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REF u8 4
TACO_ADD
  TACA_FRAME u8 0
  TACA_IMM i4 4
TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REF u8 6
TACO_ASSIGN
  TACA_FRAME u8 is_addr 16
  TACA_REF u8 6
TACO_ADD
  TACA_FRAME u8 0
  TACA_IMM i4 0
TACO_ADD
  TACA_FRAME u8 0
  TACA_IMM i4 4
TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REF u8 10
TACO_ASSIGN
  TACA_FRAME u8 is_addr 24
  TACA_REF u8 9
TACO_SUB
  TACA_FRAME u8 0
  TACA_IMM i4 4
TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REF u8 13
TACO_SUB
  TACA_FRAME u8 0
  TACA_IMM i4 4
TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REF u8 15
TACO_SUB
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 17
TACO_SUB
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 19
TACO_ADD
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 21
TACO_ADD
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 23
TACO_MUL
  TACA_FRAME i4 8
  TACA_IMM i4 2
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 25
TACO_MUL
  TACA_FRAME i4 8
  TACA_IMM i4 2
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 27
TACO_IMOD
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 29
TACO_IMOD
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 31
TACO_IDIV
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 33
TACO_IDIV
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 35
TACO_ASSIGN
  TACA_FRAME u4 is_addr 32
  TACA_IMM i4 1
TACO_DIV
  TACA_FRAME u4 32
  TACA_IMM i4 2
TACO_ASSIGN
  TACA_FRAME u4 is_addr 32
  TACA_REF u4 38
TACO_DIV
  TACA_FRAME u4 32
  TACA_IMM i4 2
TACO_ASSIGN
  TACA_FRAME u4 is_addr 32
  TACA_REF u4 40
TACO_MUL
  TACA_FRAME u4 32
  TACA_IMM i4 2
TACO_ASSIGN
  TACA_FRAME u4 is_addr 32
  TACA_REF u4 42
TACO_MUL
  TACA_FRAME u4 32
  TACA_IMM i4 2
TACO_ASSIGN
  TACA_FRAME u4 is_addr 32
  TACA_REF u4 44
TACO_MOD
  TACA_FRAME u4 32
  TACA_IMM i4 2
TACO_ASSIGN
  TACA_FRAME u4 is_addr 32
  TACA_REF u4 46
TACO_MOD
  TACA_FRAME u4 32
  TACA_IMM i4 2
TACO_ASSIGN
  TACA_FRAME u4 is_addr 32
  TACA_REF u4 48
