TACO_ASSIGN 8
  TACA_FRAME is_addr
  TACA_IMM i4 0
TACO_ASSIGN 4
  TACA_FRAME is_addr 8
  TACA_IMM i4 0
TACO_ASSIGN 2
  TACA_FRAME is_addr 12
  TACA_IMM i4 0
TACO_ASSIGN 1
  TACA_FRAME is_addr 14
  TACA_IMM i4 0
TACO_ADD
  TACA_FRAME i8
  TACA_IMM i4 8
TACO_ASSIGN 4
  TACA_FRAME is_addr 8
  TACA_REF i8 4
TACO_ADD
  TACA_FRAME i4 8
  TACA_IMM i4 8
TACO_ASSIGN 4
  TACA_FRAME is_addr 8
  TACA_REF i4 6
TACO_ADD
  TACA_FRAME i2 12
  TACA_IMM i4 8
TACO_ASSIGN 4
  TACA_FRAME is_addr 8
  TACA_REF i4 8
TACO_ADD
  TACA_FRAME i1 14
  TACA_IMM i4 8
TACO_ASSIGN 4
  TACA_FRAME is_addr 8
  TACA_REF i4 10
TACO_ASSIGN 8
  TACA_FRAME is_addr 32
  TACA_FRAME is_addr 22
