TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REG u8 REG_RDI
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REG i4 REG_RSI
TACO_ADD
  TACA_FRAME u8 0
  TACA_IMM i4 4
TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REF u8 2
TACO_SUB
  TACA_FRAME u8 0
  TACA_IMM i4 4
TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REF u8 4
TACO_ADD
  TACA_FRAME u8 0
  TACA_IMM i4 4
TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REF u8 6
TACO_ASSIGN
  TACA_FRAME u8 is_addr 16
  TACA_REF u8 6
TACO_ADD
  TACA_FRAME u8 0
  TACA_IMM i4 0
TACO_ADD
  TACA_FRAME u8 0
  TACA_IMM i4 4
TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REF u8 10
TACO_ASSIGN
  TACA_FRAME u8 is_addr 24
  TACA_REF u8 9
TACO_SUB
  TACA_FRAME u8 0
  TACA_IMM i4 4
TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REF u8 13
TACO_SUB
  TACA_FRAME u8 0
  TACA_IMM i4 4
TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REF u8 16
TACO_SUB
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 18
TACO_SUB
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 20
TACO_ADD
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 22
TACO_ADD
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 24
TACO_MOD
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 26
TACO_MOD
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 28
TACO_DIV
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 30
TACO_DIV
  TACA_FRAME i4 8
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 32
