TACO_ASSIGN
  TACA_FRAME i8 is_addr 0
  TACA_IMM i4 0
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_IMM i4 0
TACO_ASSIGN
  TACA_FRAME i2 is_addr 12
  TACA_IMM i4 0
TACO_ASSIGN
  TACA_FRAME i1 is_addr 14
  TACA_IMM i4 0
TACO_ADD
  TACA_FRAME i8 0
  TACA_IMM i4 8
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i8 4
TACO_ADD
  TACA_FRAME i4 8
  TACA_IMM i4 8
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 6
TACO_ADD
  TACA_FRAME i2 12
  TACA_IMM i4 8
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 8
TACO_ADD
  TACA_FRAME i1 14
  TACA_IMM i4 8
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 10
TACO_ASSIGN
  TACA_FRAME u8 is_addr 32
  TACA_FRAME u0 is_addr 22
