TACO_ASSIGN 1
  TACA_FRAME is_addr
  TACA_IMM i4 10
TACO_ASSIGN 1
  TACA_FRAME is_addr
  TACA_IMM i4 11
TACO_ASSIGN 4
  TACA_FRAME is_addr 4
  TACA_FRAME i1
TACO_ASSIGN 4
  TACA_FRAME is_addr 4
  TACA_FRAME i1
TACO_ASSIGN 8
  TACA_FRAME is_addr 8
  TACA_FRAME is_addr
TACO_ADD
  TACA_FRAME i1
  TACA_IMM i4 1
TACO_ASSIGN 1
  TACA_FRAME is_addr
  TACA_REF i1 5
TACO_ASSIGN 6
  TACA_FRAME is_addr 16
  TACA_CONST u6 0
TACO_ASSIGN 8
  TACA_FRAME is_addr 24
  TACA_FRAME is_addr 16
TACO_MUL
  TACA_FRAME i1
  TACA_IMM i4 2
TACO_ASSIGN 8
  TACA_FRAME is_addr 32
  TACA_REF i4 9
TACO_MUL
  TACA_FRAME u8 32
  TACA_IMM i4 2
TACO_ASSIGN 8
  TACA_FRAME is_addr 40
  TACA_REF u8 11
