TACO_ASSIGN 4
  TACA_FRAME is_addr
  TACA_IMM i4 4294967294
TACO_ASSIGN 4
  TACA_FRAME is_addr 4
  TACA_IMM i4 4
TACO_ASSIGN 4
  TACA_FRAME is_addr 8
  TACA_IMM i4 8
TACO_ASSIGN 8
  TACA_FRAME is_addr 32
  TACA_FRAME is_addr 20
TACO_ASSIGN 8
  TACA_FRAME is_addr 32
  TACA_FRAME is_addr 12
TACO_ASSIGN 4
  TACA_FRAME is_addr 40
  TACA_IMM i4 2
TACO_ASSIGN 4
  TACA_FRAME is_addr 44
  TACA_IMM i4 1
TACO_ASSIGN 4
  TACA_FRAME is_addr 48
  TACA_FRAME i4
TACO_BRZ
  TACA_FRAME i4
  TACA_ALABEL 1
TACO_ASSIGN 4
  TACA_FRAME is_addr 48
  TACA_IMM i4 0
TACO_LABEL
  TACA_ALABEL 1
  TACA_VOID
TACO_NEQ
  TACA_FRAME i4 48
  TACA_IMM i4 0
TACO_BRZ
  TACA_REF i4 11
  TACA_ALABEL 0
TACO_ASSIGN 4
  TACA_FRAME is_addr 48
  TACA_IMM i4 5
TACO_LABEL
  TACA_ALABEL 0
  TACA_VOID
TACO_ASSIGN 4
  TACA_FRAME is_addr 52
  TACA_IMM i4 5
