TACO_CALL
  TACA_LNAME is_addr f
  TACA_IMM i4 0
TACO_CALL
  TACA_LNAME u8 g
  TACA_IMM i4 0
TACO_CALL
  TACA_NAME is_addr h
  TACA_IMM i4 0
TACO_CALL
  TACA_NAME u8 i
  TACA_IMM i4 0
TACO_ASSIGN 8
  TACA_LNAME is_addr g
  TACA_LNAME is_addr f
TACO_ASSIGN 8
  TACA_LNAME is_addr g
  TACA_LNAME u8 g
TACO_ASSIGN 8
  TACA_LNAME is_addr g
  TACA_NAME is_addr h
TACO_ASSIGN 8
  TACA_LNAME is_addr g
  TACA_NAME u8 i