TACO_ASSIGN 8
  TACA_FRAME is_addr
  TACA_REG u8 REG_RDI
TACO_ASSIGN 32
  TACA_FRAME is_addr 8
  TACA_IMM i4 0
TACO_ASSIGN 4
  TACA_FRAME is_addr 8
  TACA_IMM i4 0
TACO_ASSIGN 136
  TACA_FRAME is_addr 40
  TACA_IMM i4 0
TACO_ADD
  TACA_FRAME u8
  TACA_IMM i4 8
TACO_ASSIGN 8
  TACA_FRAME is_addr 40
  TACA_REF u8 4
