TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REG u8 REG_RDI
TACO_ASSIGN
  TACA_FRAME u32 is_addr 8
  TACA_IMM i4 0
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_IMM i4 0
TACO_ASSIGN
  TACA_FRAME u136 is_addr 40
  TACA_IMM i4 0
TACO_ADD
  TACA_FRAME u8 0
  TACA_IMM i4 8
TACO_ASSIGN
  TACA_FRAME u8 is_addr 40
  TACA_REF u0 is_addr 4
