TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_LNAME u0 is_addr mode
TACO_ADD
  TACA_LNAME u0 is_addr mode
  TACA_IMM i4 0
TACO_LOAD
  TACA_FRAME u8 8
  TACA_REF u8 1
TACO_ASSIGN
  TACA_REG u8 is_addr REG_RAX
  TACA_FRAME u0 is_addr 8
TACO_RETURN
  TACA_VOID
  TACA_VOID
