TACO_ASSIGN 8
  TACA_FRAME is_addr
  TACA_LNAME is_addr mode
TACO_ADD
  TACA_LNAME is_addr mode
  TACA_IMM i4 5
TACO_ASSIGN 8
  TACA_REG is_addr REG_RAX
  TACA_REF u8 1
TACO_RETURN
  TACA_VOID
  TACA_VOID
