TACO_ASSIGN
  TACA_FRAME i4 is_addr 0
  TACA_REG i4 REG_RDI
TACO_ASSIGN
  TACA_FRAME u8 is_addr 8
  TACA_REG u8 REG_RSI
TACO_ASSIGN
  TACA_REG i4 is_addr REG_RAX
  TACA_FRAME i4 0
TACO_RETURN
  TACA_VOID
  TACA_VOID
