TACO_ASSIGN 4
  TACA_FRAME is_addr
  TACA_REG i4 REG_RDI
TACO_ASSIGN 8
  TACA_FRAME is_addr 8
  TACA_REG u8 REG_RSI
TACO_ASSIGN 4
  TACA_REG is_addr REG_RAX
  TACA_FRAME i4
TACO_RETURN
  TACA_VOID
  TACA_VOID
