TACO_ASSIGN 8
  TACA_FRAME is_addr
  TACA_REG u8 REG_RDI
TACO_ASSIGN 8
  TACA_FRAME is_addr 8
  TACA_REG u8 REG_RSI
TACO_ASSIGN 8
  TACA_REG is_addr REG_RDI
  TACA_FRAME u8
TACO_ASSIGN 8
  TACA_REG is_addr REG_RSI
  TACA_CONST is_addr 0
TACO_ASSIGN 8
  TACA_REG is_addr REG_RDX
  TACA_FRAME u8 8
TACO_CALL
  TACA_NAME is_addr cg_debug
  TACA_IMM i4 3
