TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REG u8 REG_RDI
TACO_ASSIGN
  TACA_FRAME u8 is_addr 8
  TACA_REG u8 REG_RSI
TACO_ASSIGN
  TACA_REG u8 is_addr REG_RDI
  TACA_FRAME u8 0
TACO_ASSIGN
  TACA_REG u8 is_addr REG_RSI
  TACA_CONST u0 is_addr 0
TACO_ASSIGN
  TACA_REG u8 is_addr REG_RDX
  TACA_FRAME u8 8
TACO_CALL
  TACA_NAME u0 is_addr cg_debug
  TACA_IMM i4 3
