TACO_ASSIGN
  TACA_REG u8 is_addr REG_RDI
  TACA_IMM i4 10
TACO_CALL
  TACA_NAME u0 is_addr ii_call
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_REG u8 is_addr REG_RDI
  TACA_FRAME u0 is_addr 32
TACO_ASSIGN
  TACA_REG u8 is_addr REG_RSI
  TACA_IMM i4 5
TACO_CALL
  TACA_NAME u0 is_addr mi_call
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_PARAM u32 is_addr 0
  TACA_FRAME u32 32
TACO_ASSIGN
  TACA_REG u8 is_addr REG_RDI
  TACA_FRAME u0 is_addr 0
TACO_CALL
  TACA_NAME u0 is_addr mm_call
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_PARAM u32 is_addr 0
  TACA_FRAME u32 0
TACO_CALL
  TACA_NAME u0 is_addr im_call
  TACA_IMM i4 1
TACO_CALL
  TACA_NAME u8 f
  TACA_IMM i4 0
