TACO_ASSIGN 8
  TACA_FRAME is_addr
  TACA_REG u8 REG_RDI
TACO_ASSIGN 20
  TACA_PARAM is_addr
  TACA_FRAME u20 8
TACO_ASSIGN 8
  TACA_REG is_addr REG_RDI
  TACA_FRAME u8
TACO_CALL
  TACA_NAME is_addr f
  TACA_IMM i4 2
