TACO_ASSIGN
  TACA_FRAME u8 is_addr 0
  TACA_REG u8 REG_RDI
TACO_ASSIGN
  TACA_PARAM u20 is_addr 0
  TACA_FRAME u20 8
TACO_ASSIGN
  TACA_REG u8 is_addr REG_RDI
  TACA_FRAME u8 0
TACO_CALL
  TACA_NAME u0 is_addr f
  TACA_IMM i4 2
