TACO_ADD
  TACA_FRAME i1 0
  TACA_IMM i4 0
TACO_ADD
  TACA_FRAME i1 0
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME i1 is_addr 0
  TACA_REF i1 1
TACO_ADD
  TACA_REF i1 0
  TACA_IMM i4 0
TACO_ASSIGN
  TACA_FRAME i4 is_addr 4
  TACA_REF i4 3
TACO_ADD
  TACA_FRAME i1 0
  TACA_IMM i4 0
TACO_ADD
  TACA_IMM i4 2
  TACA_REF i4 5
TACO_ASSIGN
  TACA_FRAME i4 is_addr 8
  TACA_REF i4 6
TACO_SUB
  TACA_IMM i4 0
  TACA_IMM i4 1
TACO_ASSIGN
  TACA_FRAME u4 is_addr 12
  TACA_REF u1 8
