TACO_ADD
  TACA_FRAME i1
  TACA_IMM i4 0
TACO_ADD
  TACA_FRAME i1
  TACA_IMM i4 1
TACO_ASSIGN 1
  TACA_FRAME is_addr
  TACA_REF i1 1
TACO_ADD
  TACA_REF i1 0
  TACA_IMM i4 0
TACO_ASSIGN 4
  TACA_FRAME is_addr 4
  TACA_REF i4 3
TACO_ADD
  TACA_FRAME i1
  TACA_IMM i4 0
TACO_ADD
  TACA_IMM i4 2
  TACA_REF i4 5
TACO_ASSIGN 4
  TACA_FRAME is_addr 8
  TACA_REF i4 6
TACO_ASSIGN 4
  TACA_FRAME is_addr 12
  TACA_IMM i4 255
