TACO_ASSIGN
  TACA_FRAME i4 is_addr 0
  TACA_REG i4 REG_RDI
TACO_JUMP
  TACA_ALABEL u0 unknown
  TACA_VOID
TACO_LABEL
  TACA_ALABEL u0 unknown
  TACA_VOID
TACO_ASSIGN
  TACA_REG i4 is_addr REG_RAX
  TACA_IMM i4 10
TACO_RETURN
  TACA_VOID
  TACA_VOID
TACO_LABEL
  TACA_ALABEL u0 unknown
  TACA_VOID
TACO_ASSIGN
  TACA_REG i4 is_addr REG_RAX
  TACA_IMM i4 20
TACO_RETURN
  TACA_VOID
  TACA_VOID
TACO_LABEL
  TACA_ALABEL u0 unknown
  TACA_VOID
TACO_ASSIGN
  TACA_REG i4 is_addr REG_RAX
  TACA_IMM i4 30
TACO_RETURN
  TACA_VOID
  TACA_VOID
TACO_JUMP
  TACA_ALABEL u0 unknown
  TACA_VOID
TACO_LABEL
  TACA_ALABEL u0 unknown
  TACA_VOID
TACO_ASSIGN
  TACA_REG u8 is_addr REG_RCX
  TACA_FRAME i4 0
TACO_CTBZ
  TACA_IMM i4 1
  TACA_ALABEL u0 unknown
TACO_CTBZ
  TACA_IMM i4 2
  TACA_ALABEL u0 unknown
TACO_JUMP
  TACA_ALABEL u0 unknown
  TACA_VOID
TACO_LABEL
  TACA_ALABEL u0 unknown
  TACA_VOID
