TACO_ASSIGN 4
  TACA_FRAME is_addr
  TACA_REG i4 REG_RDI
TACO_JUMP
  TACA_ALABEL 1
  TACA_VOID
TACO_LABEL
  TACA_ALABEL 2
  TACA_VOID
TACO_ASSIGN 4
  TACA_REG is_addr REG_RAX
  TACA_IMM i4 10
TACO_RETURN
  TACA_VOID
  TACA_VOID
TACO_LABEL
  TACA_ALABEL 3
  TACA_VOID
TACO_ASSIGN 4
  TACA_REG is_addr REG_RAX
  TACA_IMM i4 20
TACO_RETURN
  TACA_VOID
  TACA_VOID
TACO_LABEL
  TACA_ALABEL 4
  TACA_VOID
TACO_ASSIGN 4
  TACA_REG is_addr REG_RAX
  TACA_IMM i4 30
TACO_RETURN
  TACA_VOID
  TACA_VOID
TACO_JUMP
  TACA_ALABEL 0
  TACA_VOID
TACO_LABEL
  TACA_ALABEL 1
  TACA_VOID
TACO_ASSIGN 8
  TACA_REG is_addr REG_RCX
  TACA_FRAME i4
TACO_CTBZ
  TACA_IMM i4 1
  TACA_ALABEL 2
TACO_CTBZ
  TACA_IMM i4 2
  TACA_ALABEL 3
TACO_JUMP
  TACA_ALABEL 4
  TACA_VOID
TACO_LABEL
  TACA_ALABEL 0
  TACA_VOID
